[package]
name = "ansi2png-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-parser = "0.8.0"
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
