[package]
name = "ansi2png-rs"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]

description = "Convert ansi output to pngs"
license = "MIT"

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
imageproc = "0.22"
rusttype = "0.9"
structopt = "0.3"
vte = "0.10"
