#!/usr/bin/env bash

tmpfile="$(mktemp)"

cargo build --release

# From https://stackoverflow.com/a/42621724
script --quiet --return "${tmpfile}" --command 'rsync -aPh archlinux.thaller.ws::archlinux/lastsync /tmp/lastsync' > rsync.ansi

../target/release/ansi2png-rs -i rsync.ansi -o rsync.png

rm "${tmpfile}"
